# Docker Compose
version: "3.0"

# Define services
services:
  # symfony service
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "66:80"
    container_name: mce_camp_symf_cont
    depends_on:
      - database
    restart: always
    environment:
      DATABASE_URL: "mysql://root:pass_123+@database:3336/amssymfonyv2?serverVersion=mariadb-10.4.11"
    networks:
      - camp_net

  # Database Service(Mysql)
  database:
    image: mysql
    ports:
      - "3306:3336"
    container_name: mce_camp_symf_db
    volumes:
      - db_camp:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: amssymfonyv2
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass_123+
    networks:
      - camp_net

  # phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin
    container_name: mce_camp_symf_phpad
    depends_on:
      - database
    restart: always
    ports:
      - 4406:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - camp_net

# Dec vol
volumes:
  db_camp:

# Dec net
networks:
  camp_net:
